image:
  file: .gitpod.dockerfile
ports:
  - port: 19000-19002
tasks:
  - before: yarn install
    command: yarn tunnel
vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==