language: java

services:
  - docker

before_install:
- docker pull reactnativecommunity/react-native-android

script:
- docker run --rm --name rn-env reactnativecommunity/react-native-android bash -c "yarn add global expo-cli"
- docker run --rm --name rn-build -v $PWD:/pwd -w /pwd reactnativecommunity/react-native-android bash -c "yarn install && yarn t"