import { StyleSheet, Platform } from "react-native";

export const ACCENT = "#1a5c2e";
export const RECORDING_COLOR = "#d32f2f";

export const styles = StyleSheet.create({
  container: { flex: 1 },

  // Header
  header: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  headerBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  headerTitle: { fontSize: 17, fontWeight: "700" },
  headerRight: { flexDirection: "row", gap: 4 },

  // Profile bar
  profileBar: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 8,
  },
  profileBarContent: {
    paddingHorizontal: 12,
    gap: 8,
    alignItems: "center",
  },
  profileChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    gap: 6,
  },
  profileChipText: { fontSize: 13, fontWeight: "600", maxWidth: 120 },
  profileChipCount: { fontSize: 11, fontWeight: "500" },
  addChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },

  // Toolbar
  toolbar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  toolBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  toolBtnText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  toolBtnOutline: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
  },
  toolBtnOutlineText: { fontSize: 12, fontWeight: "500", flex: 1 },
  toolIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },

  // List
  listContent: {
    padding: 10,
    paddingBottom: 100,
  },

  // Card
  card: {
    borderRadius: 12,
    marginBottom: 8,
    overflow: "hidden",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 4,
    gap: 6,
  },
  checkbox: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  cardSura: { fontSize: 14, fontWeight: "700" },
  cardAya: { fontSize: 13, fontWeight: "600" },
  cardPage: { fontSize: 11 },
  playingBadge: {
    marginLeft: "auto",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  cardAyahText: {
    fontSize: 16,
    lineHeight: 28,
    textAlign: "right",
    writingDirection: "rtl",
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontFamily: Platform.OS === "ios" ? "Geeza Pro" : undefined,
  },
  cardActions: {
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  actionBtn: {
    flex: 1,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  noteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  noteText: { flex: 1, fontSize: 12, lineHeight: 16 },

  // Card simplified (new simplified card for refactored version)
  cardBody: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  cardSuraBadge: {
    backgroundColor: "rgba(26,92,46,0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  cardSuraBadgeText: { fontSize: 12, fontWeight: "700", color: ACCENT },
  cardAyaBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  cardTextPreview: {
    flex: 1,
    fontSize: 15,
    lineHeight: 24,
    textAlign: "right",
    writingDirection: "rtl",
    fontFamily: Platform.OS === "ios" ? "Geeza Pro" : undefined,
  },
  cardPlayBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },

  // Empty
  emptyCard: {
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 48,
    alignItems: "center",
    gap: 12,
    marginTop: 24,
  },
  emptyText: { fontSize: 15, fontWeight: "500", textAlign: "center" },
  emptyBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 8,
  },
  emptyBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },

  // Bottom bar
  bottomBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
    borderTopWidth: 1,
    paddingBottom: Platform.OS === "ios" ? 24 : 8,
  },
  bottomBarCount: { fontSize: 12, fontWeight: "500" },
  bottomBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 4,
  },
  bottomBtnText: { color: "#fff", fontSize: 13, fontWeight: "700" },

  // Modals shared
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  centerModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  centerModalContent: {
    width: "100%",
    borderRadius: 20,
    padding: 24,
  },
  helpModalContent: {
    width: "100%",
    borderRadius: 20,
    padding: 24,
    gap: 16,
  },
  helpHeader: {
    alignItems: "center",
    gap: 10,
  },
  helpTitle: {
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  helpBody: {
    fontSize: 14,
    lineHeight: 24,
    textAlign: "left",
  },
  helpCloseBtn: {
    paddingVertical: 11,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 4,
  },
  helpCloseBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
    textAlign: "center",
  },
  modalInput: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 20,
    textAlign: "right",
  },
  noteModalInput: {
    height: 120,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    fontSize: 15,
    marginBottom: 20,
    textAlign: "right",
  },
  modalButtons: { flexDirection: "row", gap: 10 },
  modalBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  modalBtnText: { fontSize: 15, fontWeight: "700" },
  modalHandle: { alignItems: "center", paddingVertical: 8 },
  handleBar: { width: 40, height: 4, borderRadius: 2 },

  // Profile modal
  profileModalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "70%",
    paddingTop: 8,
  },
  profileModalScroll: { maxHeight: 300 },
  profileModalItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  profileModalInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  profileModalName: { fontSize: 15, fontWeight: "600" },
  profileModalCount: { fontSize: 12, marginTop: 1 },
  profileModalActions: { flexDirection: "row", gap: 6 },
  pmBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  profileModalCreate: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    marginHorizontal: 20,
    marginVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  profileModalCreateText: { color: "#fff", fontSize: 14, fontWeight: "700" },
  profileModalClose: {
    padding: 16,
    alignItems: "center",
    borderTopWidth: 1,
  },
  profileModalCloseText: { fontSize: 16, fontWeight: "700" },

  // Reciter modal
  reciterItem: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    alignItems: "center",
  },
  reciterItemText: { fontSize: 15, flex: 1, textAlign: "right" },

  // Detail modal (RecordingDetailModal)
  detailOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  detailSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingTop: 8,
    paddingBottom: Platform.OS === "ios" ? 34 : 16,
  },
  detailHandle: {
    alignItems: "center",
    paddingVertical: 8,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 12,
    gap: 8,
  },
  detailAyahText: {
    fontSize: 20,
    lineHeight: 36,
    textAlign: "right",
    writingDirection: "rtl",
    paddingHorizontal: 20,
    paddingVertical: 12,
    fontFamily: Platform.OS === "ios" ? "Geeza Pro" : undefined,
  },
  detailActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 10,
  },
  detailActionBtn: {
    width: "47%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  detailActionLabel: {
    fontSize: 14,
    fontWeight: "600",
  },
  detailDivider: {
    height: StyleSheet.hairlineWidth,
    marginHorizontal: 20,
    marginVertical: 4,
  },

  // Record New modal
  recordNewSheet: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "90%",
    paddingTop: 8,
    paddingBottom: Platform.OS === "ios" ? 34 : 16,
  },
  suraPickerList: {
    maxHeight: 300,
    paddingHorizontal: 16,
  },
  suraPickerItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderRadius: 8,
  },
  ayaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  ayaGridItem: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  modeToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  modeToggleBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
  },
  recordFab: {
    position: "absolute",
    bottom: 24,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
});
